tap "daipeihust/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "sanemat/font"
tap "koekeishiya/formulae"

brew "anyenv"
brew "rustup-init"
brew "tig"
brew "tldr"
brew "daipeihust/tap/im-select"
brew "sanemat/font/ricty"
brew "silicon"
brew "koekeishiya/formulae/yabai"
brew "koekeishiya/formulae/skhd"

cask "asana"
cask "clipy"
cask "discord"
cask "pushplaylabs-sidekick"
